### ISSUE TITLE
English pages are broken

### ISSUE THREAD

**Issue by Feliix42** [fsr/ese-website#40] opened 2016-06-22 13:55 UTC
All english pages reachable from the top navigation bar are broken at the moment (e.g. [this](http://fsr.github.io/ese-website/en/faq.html)). 
It seems that there is no css theme being used, it's just plain rendered Markdown.

**Comment by JustusAdam** [comment] 2016-06-22 14:48
Naw dog, this is not a css issue. If you look at the source there's not even any basic layout being applied. Very odd.

**Comment by Feliix42** [comment] 2016-06-22 14:56
This is what I meant when I wrote "there is no css theme being used" :smile:

**Comment by JustusAdam** [comment] 2016-06-22 15:10
Then be more precise in your error reports. 😝 The better the error description, the faster it can be fixed.

**Comment by JustusAdam** [comment] 2016-06-22 15:11
Fixed by merging master.

**Comment by JustusAdam** [comment] 2016-06-22 15:48
Issue is not fixed.
Narrowed the problem down to a change in jekyll 3.
It does not occur with jekyll 2.5 but github pages doesn't care which jekyll version we specify in the Gemfile.lock.

It seems the issue is that the old selection rules for defaults don't work the same way anymore.
As far as the documentation is concerned nothing has changed however.
I am attempting to use a newer version of jekyll with bundler now to try and recreate the bug.

**Comment by JustusAdam** [comment] 2016-06-22 15:55
I have found the issue.
The `git-metadata` package is incompatible with jekyll 3, it requires jekyll 2. Hence bundler won't let me install jekyll 3. this also explains why the commit hashes are missing on cacheable resources on github pages.

**Comment by kiliankoe** [comment] 2016-06-22 18:22
> github pages doesn't care which jekyll version we specify

Just fyi: https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0

**Comment by JustusAdam** [comment] 2016-06-22 21:32
Oh yeah I forgot. I fixed this with the hotfix 674cdc2b42b03b6ec77cdadac7ebcd9bfb43e24.

**Closed by JustusAdam** 2016-06-22 21:32 UTC
Labels: bug
